spring:
  main:
    banner-mode: OFF
logging:
  level:
    org.springframework.web: DEBUG

  pattern:
    console: "[Java] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "[Java] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    name: log/java.log
    
server:
  port : 8080
  
springdoc:
  swagger-ui:
    supported-submit-methods:
    - get
    
management:
  metrics:
    export:
      elastic:
        step: 30s
        host: http://localhost:9200